package fr.bl.drit.flow.agent;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

public final class MethodIdRegistry {
  private final Map<String, Long> keyToId;
  private final AtomicLong nextId;

  public MethodIdRegistry() {
    this.keyToId = new ConcurrentHashMap<>();
    this.nextId = new AtomicLong(0);
  }

  /**
   * Initialize registry from existing file, to preserve or optimize method IDs across runs.
   *
   * @param input File containing lines of "key=id" generated by {@link #dump(File)} in a previous
   *     run.
   * @throws IOException
   */
  public MethodIdRegistry(File input) throws IOException {
    this.keyToId = new ConcurrentHashMap<>();
    long max = -1L;

    try (BufferedReader r = new BufferedReader(new FileReader(input))) {
      String line;
      while ((line = r.readLine()) != null) {
        int eq = line.indexOf('=');
        String key = line.substring(0, eq);
        long id = Long.parseLong(line.substring(eq + 1));
        this.keyToId.put(key, id);
        if (id > max) {
          max = id;
        }
      }
    }

    this.nextId = new AtomicLong(max + 1);
  }

  public long idFor(String key) {
    return keyToId.computeIfAbsent(key, k -> nextId.getAndIncrement());
  }

  public int size() {
    return keyToId.size();
  }

  /**
   * Dump the registry to a file, for potential reuse in future runs. Format is lines of "key=id".
   *
   * @param output
   * @throws IOException
   */
  public void dump(File output) throws IOException {
    try (BufferedWriter w = new BufferedWriter(new FileWriter(output))) {
      for (Map.Entry<String, Long> entry : keyToId.entrySet()) {
        w.write(entry.getKey());
        w.write('=');
        w.write(entry.getValue().toString());
        w.write('\n'); // no cr
      }
    }
  }
}
