package fr.bl.drit.flow.agent;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Mapping of method keys (e.g. "com.example.MyClass#myMethod(Ljava/lang/String;)V") to numeric IDs
 * used in the recorded traces. This is thread-safe and assigns new IDs on demand. The mapping can
 * be initialized from an existing file to preserve or optimize method IDs across runs, and can be
 * dumped to a file for future reuse.
 */
public final class MethodIdMapping {
  private final Map<String, Long> keyToId;
  private final AtomicLong nextId;

  /** Initialize a blank mapping. */
  public MethodIdMapping() {
    this.keyToId = new ConcurrentHashMap<>();
    this.nextId = new AtomicLong(0);
  }

  /**
   * Initialize mapping from an existing file, to preserve or optimize method IDs across runs.
   *
   * @param input Path to file containing lines of "key=id" generated by {@link #dump(Path)} in a
   *     previous run.
   * @throws IOException
   */
  public MethodIdMapping(Path input) throws IOException {
    this.keyToId = new ConcurrentHashMap<>();
    long max = -1L;

    try (BufferedReader r = Files.newBufferedReader(input)) {
      String line;
      while ((line = r.readLine()) != null) {
        int eq = line.indexOf('=');
        String key = line.substring(0, eq);
        long id = Long.parseLong(line.substring(eq + 1));
        this.keyToId.put(key, id);
        if (id > max) {
          max = id;
        }
      }
    }

    this.nextId = new AtomicLong(max + 1);
  }

  public long idFor(String key) {
    return keyToId.computeIfAbsent(key, k -> nextId.getAndIncrement());
  }

  public int size() {
    return keyToId.size();
  }

  /**
   * Dump the mapping to a file, for potential reuse in future runs. Format is lines of "key=id".
   */
  public void dump(Path output) throws IOException {
    dump(keyToId, output);
  }

  public static void dump(Map<String, Long> mapping, Path output) throws IOException {
    try (BufferedWriter w =
        Files.newBufferedWriter(
            output,
            StandardOpenOption.CREATE,
            StandardOpenOption.WRITE,
            StandardOpenOption.TRUNCATE_EXISTING)) {
      for (Map.Entry<String, Long> entry : mapping.entrySet()) {
        w.write(entry.getKey());
        w.write('=');
        w.write(entry.getValue().toString());
        w.write('\n'); // only LF
      }
    }
  }
}
